apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: lbastetpipelinesjavascriptdocker 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: lbastetpipelinesjavascriptdocker 
    spec:
      containers:
        - name: lbastetpipelinesjavascriptdocker 
          image: akscontainerlb.azurecr.io/lbastetpipelinesjavascriptdocker
          ports:
          - containerPort: 8080